### ISSUE TITLE
[Package Request] - cryptopp

### ISSUE THREAD

**Issue by talawahtech** [amazonlinux/amazon-linux-2023#117]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
>Crypto++ is a free C++ Class Library of Cryptographic Schemes

https://github.com/weidai11/cryptopp

**Is this an update to existing package or new package request?**
New package.

**Is this package available in Amazon Linux 2?**
Yes, cryptopp and cryptopp-devel are available via EPEL. They are also available in Fedora 34.

**Number of users impacted**
cryptopp-devel is a dependency of the Seastar server framework http://seastar.io/.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by stewartsmith** [comment]
We're not looking to add more cryptographic libraries to Amazon Linux. We have too many already! We prefer to focus in on OpenSSL, and have switched several packages over to build with OpenSSL rather than other libraries to keep this dependency graph nice and focused. Since there are FIPS implications for cryptographic libraries, adding more either increases the work to make FIPS happen, or means that more and more functionality cannot be used by customers needing FIPS.

I'm going to mark this wontfix as more cryptographic libraries aren't in our plan.
