### ISSUE TITLE
[Feature Request] - ECR Scanning

### ISSUE THREAD

**Issue by hborham** [amazonlinux/amazon-linux-2023#145]
**Is your feature request related to a problem? Please describe.**
Is there a plan to support ECR Image Scanning for AL2022

**Describe the solution you'd like**
Tried to updated from AL2 to AL2022 and noticed the scans are failing with `UnsupportedImageError: The operating system 'amzn' version '2022' is not supported`

**Describe alternatives you've considered**
Guidance on whether or not AL20xx will be on the roadmap for ECR scan

**Additional context**
N/A

**Comment by rgoltz** [comment]
Hi @hborham - I would recommend to open an issue (or two) under https://github.com/aws/containers-roadmap/issues and link this github issue with your issue here. Please note there are two scan options on ECR Scanning in AWS: Basic and Enhanced.

You can find an examples (request for support for Alpine for both ECR scan-types) - Normally the ECS team will pick-up thoese requests: https://github.com/aws/containers-roadmap/issues?q=is%3Aissue+not+supported+is%3Aclosed+Support+for+Alpine+3.16

**Comment by vahedq** [comment]
+1 This would be super awesome.

**Comment by stewartsmith** [comment]
As per https://github.com/aws/containers-roadmap/issues/1800 this is now complete.
