### ISSUE TITLE
[Package Request] - lsb_release

### ISSUE THREAD

**Issue by amrragab8080** [amazonlinux/amazon-linux-2023#184]
Some packages have a dependency on lsb_core to provide lsb_release. 
On AL2 this is provided by the system-lsb-core package - but nothing in AL2022

al2022-ami-minimal-2022.0.20220831.1-kernel-5.15-x86_64

**Comment by stewartsmith** [comment]
The modern way to check for the OS would be to look at `/etc/os-release`. 

- https://www.freedesktop.org/software/systemd/man/os-release.html is documentation for `/etc/os-release`
- http://0pointer.de/blog/projects/os-release.html for reasoning behind `/etc/os-release`
- https://bugzilla.redhat.com/show_bug.cgi?id=2012924 (for this same issue in RHEL9)

Software should migrate to parsing the standard `/etc/os-release` rather than shelling out to `lsb_release`.

We currently do not have plans to introduce `lsb_release` to Amazon Linux 2023.

I'll keep this issue open until we have some public-facing documentation (that isn't just a github issue) on this.

**Comment by daniejstriata** [comment]
LSB has been abandoned with the last release in 2015. https://lists.linuxfoundation.org/pipermail/lsb-discuss/2023-February/008278.html

Using `/etc/os-release` provides a much more intuitive method to get details about the version. I've migrated most of my internal processes to use that instead of `lsb_release`. `ID_LIKE` makes it very powerful. Here are some examples:
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
```
or

```
NAME="Rocky Linux"
VERSION="8.8 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.8 (Green Obsidian)"
```
or
```
NAME="Linux Mint"
VERSION="21.2 (Victoria)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.2"
```
I wonder if anyone ever used lsb for more than getting details about the OS.

**Comment by stewartsmith** [comment]
An update to https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html is being deployed shortly that will add details on moving to using `/etc/os-release` from `lsb_release`.

I'll resolve this issue now that the documentation has been updated.

**Comment by stewartsmith** [comment]
FYI https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#lsb-release is published now
