### ISSUE TITLE
[Bug] - pkg-config not working

### ISSUE THREAD

**Issue by fallertsen** [amazonlinux/amazon-linux-2023#202]
**Describe the bug**
The script `/usr/bin/pkg-config` is currently not working.

**To Reproduce**

```sh
$ /usr/bin/pkg-config
/usr/bin/pkg-config: line 8: /usr/bin/x86_64-redhat-linux-gnu-pkg-config: No such file or directory
```

**Expected behavior**
The error should not be there, and instead of `/usr/bin/x86_64-redhat-linux-gnu-pkg-config` it should call `/usr/bin/x86_64-amazon-linux-gnu-pkg-config`.

**Additional context**
The AMI used is `ami-0db95bd57752653ac`, which is the latest Amazon Linux 2022 AMI at the time of writing.

**Comment by stewartsmith** [comment]
Reports that we have this issue in 2022.0.20221101

**Comment by nmeyerhans** [comment]
Confirmed that this still occurs if the `amazon-rpm-config` package is not installed. It's present by default in AMIs, but is omitted from the container images, so that's likely where people will encounter it.

For now, the workaround is to `dnf install amazon-rpm-config` if you encounter this issue.

**Comment by stewartsmith** [comment]
This appears to be resolved with the latest releases? If not we can reopen, but my quick test in a container seemed to show it working: a `dnf install /usr/bin/pkg-config` pulled in `amazon-rpm-config`.
