### ISSUE TITLE
[Question] BBR TCP algorithm

### ISSUE THREAD

**Issue by skyzyx** [amazonlinux/amazon-linux-2023#263]
I'm just looking for confirmation that the BBR TCP algorithm will continue to be an option in updated kernel builds for AL2022.

In Amazon Linux 2, we do this:

```bash
# https://github.com/torvalds/linux/commit/0f8782ea14974ce992618b55f0c041ef43ed0b78
# https://github.com/google/bbr/blob/master/Presentations/bbr-2017-02-08-google-net-research-summit.pdf
# https://groups.google.com/forum/#!forum/bbr-dev

cat << EOF >> /etc/sysconfig/modules/tcpcong.modules
#! /usr/bin/env bash
exec /sbin/modprobe tcp_bbr >/dev/null 2>&1
exec /sbin/modprobe sch_fq >/dev/null 2>&1
EOF

chmod 0755 /etc/sysconfig/modules/tcpcong.modules

echo "Persist sysctl tuning"
cat /etc/sysctl.d/*.conf >> /etc/sysctl.conf
sysctl -p
```

I'm wondering:

1. Is the BBR option still available in the newer kernel builds?
1. Is BBR still the most efficient algorithm to be using for TCP traffic? Or has something superseded it in the last 5–6 years?

**Comment by daniejstriata** [comment]
I'm using the kernel released end of last year:
`5.15.86-53.137.amzn2.x86_64`

It has `bbr `enabled

**Comment by nmeyerhans** [comment]
> Is the BBR option still available in the newer kernel builds?

Yes, BBR is supported in AL2023

> Is BBR still the most efficient algorithm to be using for TCP traffic? Or has something superseded it in the last 5–6 years?

As with most such questions, the answer usually comes down to "it depends."  AL2023 doesn't currently take an opinionated position on tcp schedulers and defers to the upstream Linux defaults. BBR is available and you're encouraged to consider it for your deployment, but you should be sure to test it and understand the impact. There are some documented edge cases with BBR involving starvation of other (non BBR) flows, so that's something to consider.

> cat /etc/sysctl.d/*.conf >> /etc/sysctl.conf

This isn't necessary. Everything matching `/etc/sysctl.d/*.conf` will be loaded along with `/etc/sysctl.conf`.  See `man 5 sysctl.d`
