### ISSUE TITLE
[Package Request] - perl(Encode::Detect)

### ISSUE THREAD

**Issue by regattaman** [amazonlinux/amazon-linux-2023#266]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
php-imap, php-zip, perl-Encode::Detect

**EDIT:** https://github.com/amazonlinux/amazon-linux-2023/issues/266#issuecomment-1603316504 points to other issues for `php-imap` and `php-zip`, and keeping this issue for tracking `perl-Encode-Detect`

**Is this an update to existing package or new package request?**
new

**Is this package available in Amazon Linux 2?**
yes

current release of Linux 2022 does not contain these modules even though they are available in all prev versions of AWS Linux.

**Number of users impacted**
Required for proper functioning of our business.

**Comment by junosapien** [comment]
Definitely need php-zip and php-imap.

**Comment by TheErondu** [comment]
I need the php-zip too .. Impacts my laravel application .. Please fix

**Comment by bwaters** [comment]
please add php-zip

**Comment by paulstalvey** [comment]
Definitely php-imap.

**Comment by egovelox** [comment]
Need php-imap too please ;)

**Comment by stewartsmith** [comment]
Please see this issue and comment for `php-imap`: https://github.com/amazonlinux/amazon-linux-2023/issues/363#issuecomment-1601864494

See https://github.com/amazonlinux/amazon-linux-2023/issues/195 for `php-zip` (rather than having duplicate issues).

I'm going to keep this issue around for the `perl` `Encode::Detect` request (and change the title accordingly) but will point to the above issues for the PHP modules.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/new-AL2023.3-AL2023.4.html the `perl-Encode-Detect` package is in AL2023 as of AL2023.4. Resolving.
