### ISSUE TITLE
[Missing Documentation] - Naming Policy

### ISSUE THREAD

**Issue by dylrich** [amazonlinux/amazon-linux-2023#285]
We noticed that "Amazon Linux 2022" has become "Amazon Linux 2023". My organization had already begun producing AL2022 packages assuming the name would be "2022", even if GA was pushed to sometime in 2023. Now that the name has changed, we're not sure if we should be updating our infrastructure to change all of those names to "2023" or if we should wait. It's mainly cosmetic, but we'd prefer to use names that will be the least confusing for users long-term. I see you [have a release schedule listed here](https://docs.aws.amazon.com/linux/al2023/ug/release-cadence.html), but it doesn't mention the 2022-2023 name change. Could you provide some information on what the naming scheme of this distro series will look like in the future and if we should expect any more name changes like 2022 -> 2023 before GA?

**Comment by stewartsmith** [comment]
We won't be doing any further renames for AL2023. It will be AL2023 until its end of life. The only time we will change the name is in the next major release in 2 years time.

It is best to use the "Amazon Linux 2023" / AL2023 naming rather than AL2022, and this will provide the most clarity for the long term. The rename from AL2022 to AL2023 was a one time event for this release.

https://docs.aws.amazon.com/linux/al2023/ug/naming-and-versioning.html is what we have documented for naming for AL2023, which does not have the explicit mention that it'll remain AL2023 within the major version. I'll work with the docs team to explicitly mention this.

We also have https://docs.aws.amazon.com/linux/al2023/ug/release-cadence.html which will have a slight update to the first paragraph as it's Amazon Linux that's released every 2 years, not AL2023.

But the https://docs.aws.amazon.com/linux/al2023/ug/release-cadence.html page does document that after AL2023, the next major version will be AL2025, and both AL2023 and AL2025 will be supported simultaneously.

**Comment by dylrich** [comment]
Thanks for the clarification -- I appreciate it!
