### ISSUE TITLE
[Bug] - AWS DHCP Options set domain-name separated by "032" rather than a space

### ISSUE THREAD

**Issue by nefnohack** [amazonlinux/amazon-linux-2023#329]
**Describe the bug**
Use AWS DHCP Options set domain-name separated by "032" rather than a space

**To Reproduce**
1. create a dhcp option set with muti domain name like：
test1.com test2.com
2. just associate to VPC and run a new instance as AL2023

**Expected behavior**
the content for /etc/resolv.conf should be(search test1.com test2.com)
but it shows below:
search test1.com032test2.com

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nmeyerhans** [comment]
Hi @nefnohack. The issue here is that the VPC DHCP server sends sends the provided list of domains using DHCP option 15, which only supports a single domain name (see [RFC 2132 section 3.17](https://www.rfc-editor.org/rfc/rfc2132#section-3.17)).  When multiple domain names are provided, they're separated by a space character, which isn't valid in a domain name, so systemd-resolved replaces the space with a decimal encoding of the ascii value.

This has been observed elsewhere as well, and [this CoreOS issue](https://github.com/coreos/bugs/issues/1934#issuecomment-346345773) provides a good summary including packet captures.

The [awscli documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-dhcp-options.html) has the following to say on the topic:
> Important : Some Linux operating systems accept multiple domain names separated by spaces. However, Windows and other Linux operating systems treat the value as a single domain, which results in unexpected behavior. If your DHCP options set is associated with a VPC that has instances with multiple operating systems, specify only one domain name.

So for now, our recommendation is to follow that documentation and specify a single domain name in your DHCP option sets.

We've passed on the request to the VPC team to add full support for multiple domain names using DHCP Option 119 ([[RFC 3397, section 2](https://www.rfc-editor.org/rfc/rfc3397#section-2)) but don't have an estimate about when such support might be available.

**Comment by nefnohack** [comment]
but other linux system like amazonlinux 2 and redhat donot have this issue

**Comment by stewartsmith** [comment]
There's been a section added to our documentation on this: https://docs.aws.amazon.com/linux/al2023/ug/deprecated-al2.html#dhcp-set-domain-name-space
