### ISSUE TITLE
[Missing Documentation] - amazon-linux-extras error

### ISSUE THREAD

**Issue by amandamayra** [amazonlinux/amazon-linux-2023#340]
Hello, I'm working on a project where we use amazon-linux-extras, but after updating to AL2023 we are getting an error that it can't be found. I've seen in some forums that it has been discontinued, could you inform me if there is any substitute for this package? Or is it necessary to downgrade to Amazon Linux 2?

**Comment by stewartsmith** [comment]
The capability that `amazon-linux-extras` provided was that you could install newer versions of some packages on Amazon Linux 2. For Amazon Linux 2023, we provide these alternate versions of packages as namespaced packages in the main package repository.

For example:
The `python3` package is Python 3.9, and this is the "system python". Python 3.11 is made available in the `python3.11` package, which will give you `/usr/bin/python3.11` alongside the `/usr/bin/python3` and `/usr/bin/python3.9` provided by the `python3` package.
```
bash-5.2# dnf install -y python3.11
<snip>
bash-5.2# ls /usr/bin/python3*
/usr/bin/python3  /usr/bin/python3.11  /usr/bin/python3.9
bash-5.2# python3.11 --version
Python 3.11.2
bash-5.2# python3 --version
Python 3.9.16
```

This is also why PHP is `php8.1`, so that we can ship future versions of PHP and provide customer choice as to what major version of PHP to run. This is also the case for PostgreSQL (`postgresql15`), and MariaDB (`mariadb105`).

These alternate versions of packages follow the upstream life-cycle, which is documented here: https://docs.aws.amazon.com/linux/al2023/release-notes/support-info-by-support-statement.html

There is the "Q: Does AL2023 have Amazon-Linux-Extras like AL2?" in the FAQ (see https://aws.amazon.com/linux/amazon-linux-2023/faqs/ ) but it is missing from the https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html page. Would expanding on this topic in that part of the documentation help?

**Comment by avoidik** [comment]
could you also explain about other packages, especially those coming from `amazon-linux-extras` like `java-openjdk11`?

**Comment by stewartsmith** [comment]
https://docs.aws.amazon.com/linux/al2023/release-notes/compare-packages.html now details all of the AL2 Extras and what the updated equivalent packages are in AL2023.

For example, https://docs.aws.amazon.com/linux/al2023/release-notes/vercmp-AL2-AL2023.0.html currently has:

<img width="1242" alt="image" src="https://github.com/amazonlinux/amazon-linux-2023/assets/611883/6ead04a2-7e4c-4764-b685-e7ee6713e53b">

We also updated the summary of changes since AL2 to include Java https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#java
