### ISSUE TITLE
[Package Request] - Composer

### ISSUE THREAD

**Issue by jacques** [amazonlinux/amazon-linux-2023#371]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

composer - installs and updates dependencies for PHP applications which it fetches from various sources (git repos, zip files from htttps, etc.).

**Is this an update to existing package or new package request?**

No.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

Yes on the older Amazon Linux 2 instance:

```
# yum search composer
Failed to set locale, defaulting to C
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
293 packages excluded due to repository priority protections
================================================================================= N/S matched: composer =================================================================================
php-composer-installers.noarch : A multi-framework Composer library installer
composer.noarch : Dependency Manager for PHP
php-composer-ca-bundle.noarch : Lets you find a path to the system CA
php-composer-semver.noarch : Semver library version 1
php-composer-semver3.noarch : Semver library version 3
php-composer-spdx-licenses.noarch : SPDX licenses list and validation library
php-composer-xdebug-handler.noarch : Restarts a process without Xdebug
python2-fedmsg-atomic-composer.noarch : Composes atomic trees when Fedora repositories are updated

  Name and summary matches only, use "search all" for everything.
```

**Any additional information you'd like to include. (use-cases, etc)**

Composer is used to install dependencies for php applications.

**Comment by jacques** [comment]
Just adding a note here that #320 Is a dependency for this ticket as composer requires the php zip extension.

**Comment by BernardRobbins** [comment]
Following these instructions should get you by: https://getcomposer.org/download/ 
Composer version 2.5.8 2023-06-09 17:13:21 is running on mine.

**Comment by YoannChabert** [comment]
```

**Comment by stewartsmith** [comment]
You can now install `composer` directly from the Amazon Linux 2023 repositories. The required PHP modules are in our PHP 8.2 packages, so there's currently the restriction of it needing PHP8.2 (we should be able to address this in a future release).

The [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) will be up shortly mentioning this.

It appears that this package was in EPEL rather than Amazon Linux 2, so I'm happy to say that this is the first time that Amazon Linux is shipping Composer!
