### ISSUE TITLE
[Package Request] - libsodium

### ISSUE THREAD

**Issue by neilcook** [amazonlinux/amazon-linux-2023#377]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

libsodium

The encryption library.

**Is this an update to existing package or new package request?**

New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

It is available in Amazon Linux 2, as part of the core OS.

**Any additional information you'd like to include. (use-cases, etc)**

I am an Open-Source software developer, and I'd like to build packages for Amazon Linux 2023 for users  who are currently using Amazon Linux 2, but I need libsodium to do so.

**Comment by stewartsmith** [comment]
What packages are depending on `libsodium` that aren't also able to be built with a different library such as OpenSSL or GnuTLS?

The tl;dr here is taht cryptographic libraries are "fun" due to FIPS.

**Comment by neilcook** [comment]
I am the primary developer/maintainer of https://github.com/PowerDNS/weakforced, which uses libsodium for encrypting data that is then sent around in UDP packets. It's not TLS, I'm just using the data encryption/decryption functions. 

However I don't really understand the comment about FIPS. I don't care about FIPS.
1) That's a US standard. There is a whole world out there that isn't part of the US.
2) I've never had anyone ask about FIPS ever, and this package is in use by a lot of folks, including large telcos, even in the US

Rewriting to use e.g. libcrypto  primitives to get FIPS support when this has never come up before is unlikely at this stage.

**Comment by stewartsmith** [comment]
While we work on getting some more public documentation on all the FIPS related implications, I'll attempt to summarise a bit here:

- even though its primarily US, there's flow on effects for those who end up somewhere in the supply chain for those who end up using it. The audience is wider that you'd expect.
- We want to be able to be very clear about what running in FIPS mode means for packages and the OS, adding cryptography packages is the easiest way to make this job harder.

Ignoring FIPS, there's a few thoughts we have as distro maintainers:
- I am pretty sure that https://xkcd.com/927/ is entirely about cryptography libraries.
- Ensuring correctness and security patching for cryptographic libraries is a non-trivial amount of specialised work, and we'd rather focus those efforts on fewer libraries rather than expanding the number we have to divide resources between.

That being said, we don't like having things that are blockers for migrating from AL2 to AL2023, and I get that this particular thing has to be frustrating.

Can you point me to the bits of code calling libsodium? I'd like to get an idea of how complex a port to something we already ship is.

**Comment by BernardRobbins** [comment]
Magento 2.4.4-p1 upwards requires libsodium.
https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/composer.json

**Comment by ozbenh** [comment]
We are evaluating inclusion of this package in our next quarterly release

**Comment by ozbenh** [comment]
libsodium has now been released as part of AL2023.2
