### ISSUE TITLE
[Package Request] - libmcrypt, libmcrypt-devel

### ISSUE THREAD

**Issue by huyhoang8398** [amazonlinux/amazon-linux-2023#403]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
libmcrypt
libmcrypt-devel
php-pecl-mcrypt

**Is this an update to existing package or new package request?**
New package request.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes
**Any additional information you'd like to include. (use-cases, etc)**
More than 1 million users we serve.

**Comment by stewartsmith** [comment]
`mcrypt` is rather old, and from a quick glance at the list of ciphers offered, there's a good number of algorithms there that aren't recommended for use in modern systems. Since the `libmcrypt` library hasn't been updated since 2007, I'm pretty confident in saying it's abandonware, and as such it's unlikely something we would want to package when there are modern well maintained alternatives.

Additionally, https://www.php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt notes that mcrypt was deprecated in php 7.1.

Is porting to the openssl module a possibility?

**Comment by huyhoang8398** [comment]
Hi @stewartsmith 

We're still maintaining legacy code, and php-mcrypt is still support php > 8.1
https://pecl.php.net/package/mcrypt in PECL

But since we need libmcrypt for compiling

**Comment by stewartsmith** [comment]
This might be one of the situations where building the rpm yourself either locally or using copr, or even just building both from source is the right thing.

I'm almost certain we won't want to package it in the main Amazon Linux repositories due to the nature of it being unmaintained.

**Comment by stewartsmith** [comment]
I'm going to keep the issue open until we have some documentation updates stating why `mcrypt` and friends isn't packaged in the AL2023 repositories.

It's a possible candidate for someone in the community to build though, as part of a repository for unmaintained software or similar.

**Comment by stewartsmith** [comment]
The documentation now has information about the deprecation and removal of `mcrypt`: https://docs.aws.amazon.com/linux/al2023/ug/deprecated-al2.html#deprecated-mcrypt

Resolving this issue.

**Comment by limmike** [comment]
> We're still maintaining legacy code, and php-mcrypt is still support php > 8.1 https://pecl.php.net/package/mcrypt in PECL
> 
> But since we need libmcrypt for compiling


Not recommended, but you can compile it yourself. See [Need detailed steps to install Mcrypt (1.0.6 or 1.0.7) for PHP8.2 on Amazon Linux 2023](https://repost.aws/questions/QUQFr6C5zeQMyXHG6kz6WO9w/need-detailed-steps-to-install-mcrypt-1-0-6-or-1-0-7-for-php8-2-on-amazon-linux-2023)
