### ISSUE TITLE
[Bug] - Amazon Linux 2023 - highly unstable - needs reboot every 1/2 days being unavailable

### ISSUE THREAD

**Issue by parabinda** [amazonlinux/amazon-linux-2023#423]
**Describe the bug**
Amazon Linux 2023 unstable.

**To Reproduce**
Running my an Amazon Linux 2023 EC2 instance, since 5+ days now.
I had to restart it 3 times within these period.

**Expected behavior**
Amazon Linux 2023 Instance must be stable as advertised by AWS.
I went for Amazon Linux 2023, by promises of AWS that it is stable and performant. However, I am disillusioned now.

**Screenshots**
EC2_Failure.png

**Desktop (please complete the following information):**
 - OS: output of - uname -a 
 "Linux ip-172-31-19-27.ap-south-1.compute.internal 6.1.41-63.114.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Aug  1 20:47:25 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
"
**Smartphone (please complete the following information):**
![EC2_failure](https://github.com/amazonlinux/amazon-linux-2023/assets/22537026/2c3a1eba-f7dc-4a2f-aab7-d4da19f11e35)

**Additional context**

**Comment by stewartsmith** [comment]
This isn't something we have received reports about, so we'd really appreciate some further details so that we can verify if it's something wrong with the OS itself.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-console.html contains some useful pointers to look at the System Log for the instance (you can get this via the EC2 console). This is what has been output to the serial port and may contain hints as to what's gone on such as a kernel panic or Out Of Memory (OOM) conditions.

If you're using smaller instance types with not a lot of memory (say, less than 1 or 2 GB) then you may also be limited into what fits into RAM as a workload, leading to various Out of Memory conditions. These can be alleviated by adding swap space, or moving to a larger instance type.

If it's just the ability to connect with EC2 Instance Connect, that could also be a different issue than if it's losing all connectivity to the instance.

Before posting any output from the console, do examine it for any data that you may not want public.

**Comment by stewartsmith** [comment]
Without any further information, I'm afraid we can't look into this any further.

I'm going to close the issue, and we can reopen if there's more information.
