### ISSUE TITLE
[Bug] - Python 3.11 as default will break DNF

### ISSUE THREAD

**Issue by jdrozdnovak** [amazonlinux/amazon-linux-2023#459]
**Describe the bug**
Hello,
We noticed that when python 3.11 is installed and made default for python3 command, the DNF breaks

**To Reproduce**
dnf install python3.11
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2
sudo update-alternatives --config python3 (select 3.11)
dnf list

**Expected behavior**
DNF script should call specifically python3.9 in shebang as its compiled to work only with 3.9. 
We fixed the issue on our side by editing the shebang and now we are fine using python 3.11 as default

**Comment by stewartsmith** [comment]
We generally don't recommend doing this due to the flow on consequences (such as the one you observe here). This is certainly something that needs better documentation, thus I'm adding the `documentation` label to the issue as at the very least we should cover that in docs.

I'd like to understand the motivation of having 3.11 be `/usr/bin/python3` rather than the option.

If we were to look at making this work better, it's something I'd want us to work on in upstream Fedora first, as deviating on this from the broader ecosystem would end up being a lot of repeated pain and bugs creeping in, which wouldn't be fun for anybody.

**Comment by ozbenh** [comment]
The main issue here is that we do not ship all the python modules environment for the alternate python. Fedora doesn't do alternate pythons. There might be additional issues specific to dnf with 3.11 but the main one is that our 3.11 is bare with no module packages.

**Comment by stewartsmith** [comment]
This is now covered in https://docs.aws.amazon.com/linux/al2023/ug/python.html
