### ISSUE TITLE
Please add Support for following packages 

### ISSUE THREAD

**Issue by vkgarg2023** [amazonlinux/amazon-linux-2023#472]
For our use case,  Following packages are need in AL2023 - 
(a) Wiregarud   
(b) IPROUTE2
(c) FRR --  Open Source routing protocol package
(d) SoftflowD - https://github.com/irino/softflowd   -- Flow monitoring
(e) GRE -- Needed for Amazon CloudWAN
(f)  Libvert – For KVM support
(g) SALT minion – for automation  (apt-get install -y salt-minion salt-common )
(f)  Prometheus_node_exporter – Open-source platform for time series DB

**Comment by stewartsmith** [comment]
> For our use case, Following packages are need in AL2023
> - (a) Wiregarud

Already present, see https://github.com/amazonlinux/amazon-linux-2023/issues/167

> (b) IPROUTE2

Already packaged:
```
bash-5.2# dnf info iproute
Last metadata expiration check: 0:42:20 ago on Wed Oct  4 15:47:55 2023.
Available Packages
Name         : iproute
Version      : 5.10.0
Release      : 2.amzn2023.0.5
Architecture : aarch64
Size         : 681 k
Source       : iproute-5.10.0-2.amzn2023.0.5.src.rpm
Repository   : amazonlinux
Summary      : Advanced IP routing and network device configuration tools
URL          : http://kernel.org/pub/linux/utils/net/iproute2/
License      : GPLv2+ and Public Domain
Description  : The iproute package contains networking utilities (ip and rtmon,
             : for example) which are designed to use the advanced networking
             : capabilities of the Linux kernel.
```

> (c) FRR -- Open Source routing protocol package

Tracked in https://github.com/amazonlinux/amazon-linux-2023/issues/474

> (d) SoftflowD - https://github.com/irino/softflowd -- Flow monitoring

Tracked in https://github.com/amazonlinux/amazon-linux-2023/issues/475

> (e) GRE -- Needed for Amazon CloudWAN

As per https://github.com/amazonlinux/amazon-linux-2023/issues/478 the kernel module is already available.

> (f) Libvert – For KVM support

I assume you mean `libvirt`, and this is being tracked in https://github.com/amazonlinux/amazon-linux-2023/issues/479

> (g) SALT minion – for automation (apt-get install -y salt-minion salt-common )

Tracked in https://github.com/amazonlinux/amazon-linux-2023/issues/477

(note that `apt-get` is of course the Debian package manager, and won't be present/used for installing packages on Amazon Linux).

> (f) Prometheus_node_exporter – Open-source platform for time series DB

Tracked in https://github.com/amazonlinux/amazon-linux-2023/issues/476


Since all the asks here are either completed or tracked in their own issue, closing this one.
