### ISSUE TITLE
[Package Request] - wkhtmltopdf

### ISSUE THREAD

**Issue by skoloCFD** [amazonlinux/amazon-linux-2023#570]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
wkhtmltopdf

**Is this an update to existing package or new package request?**
New request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes

**Any additional information you'd like to include. (use-cases, etc)**
Used to converting HTML to PDF

**Comment by rbpltr** [comment]
It looks like wkhtmltopdf has been [archived by its owner](https://github.com/wkhtmltopdf). However, I have been successfully using the [Alma Linux 9 wkhtmltox packages](https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6.1-3) with Amazon Linux 2023.

For example:
```sh
dnf install -y https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox-0.12.6.1-3.almalinux9.$(uname -m).rpm
wkhtmltopdf --version
```

**Comment by stewartsmith** [comment]
Given that it's archived upstream, this isn't something we are going to look at bringing into AL2023, as the maintenance burden is likely high given its interaction with web content.

Going to add the Won't Fix tag here so that others can find it if needed.

This may be a candidate for someone to create a maintain a COPR repository for.

**Comment by thanhhiep206** [comment]
@rbpltr i still get errors after install wkhtmltox in Amazon linux 2023
`/home/ec2-user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf_centos_7_amd64: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory`

**Comment by rbpltr** [comment]
@thanhhiep206 Those errors aren't related to the binary I suggested installing. It looks like you're trying to run something that relies on a binary in a Ruby gem. I don't know how to fix that issue.

**Comment by briri** [comment]
we're running into the same issue @thanhhiep206 did you ever get around it?

**Comment by FactorGFC** [comment]
@briri @thanhhiep206 
Have you find a solution for this issue?
I've tried everything I can even with the fact of not having access to the AWS servers terminal, all I've done is testing via workflow installing packages and/or .config files on the .ebextensions but none of them have been succesful.

**Comment by briri** [comment]
@FactorGFC unfortunately no. We ended up replacing the code that was using wkhtmltopdf with puppeteer and headless chrome. 

**On the server side:**
We had to install a ton of packages (around 90) to support puppeteer and chrome which feels bad, but at least they're rpm so will get updated during normal server patching.

Once the packages were installed we need to run `npm install puppeteer` followed by `npx puppeteer browsers install chrome@stable` which will install chrome into a `.cache/puppeteer/chrome/linux-[version]` from the dir you run it in. This will install the latest stable version of chrome that (I assume) works with the version of puppeteer installed.

We setup the above to be run when we do application dependency updates (e.g. `npm upgrade`). We create a sim link to the actual chrome executable for the latest version so that the app doesn't have to worry about the specific linux version.

Everything seems to be working ok (we just deployed to prod today! 😅)

**On the application side:**
We are running a Rails app, so we have Capistrano managing that `npx` command and the sim linking mentioned above.

We swapped out the `wicked_pdf` gem which was a wrapper for wkhtmltopdf for `grover` a wrapper around puppeteer. This took some effort but it wasn't too bad. We found that the margin and font handling differed a bit from wkhtmltopdf, so we had to do some tedious tweaking to get the final PDFs to match.

We've noticed that this new approach takes almost twice as long to generate the PDF (compared to wkhtmltopdf). I suspect that this is overhead of launching chrome. We have also found that our simple PDF went from an average size of 50kb to 250kb!

We are going to experiment with the `npx puppeteer browsers install` command to see if there's a lighter footprint executable we can use.

**Comment by FactorGFC** [comment]
@briri @thanhhiep206 Friends we got it working on our project mounted on Amazon Linux 2023 (aws beanstalk) with Ruby 3.2.2
 
What we did is: 
1) Added container commands that execute on deploy inside file 01_deploy.config in the .ebextensions folder like this
      ```
        install_missing_libraries:
          command: "sudo dnf install -y https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox-0.12.6.1-3.almalinux9.$(uname -m).rpm"
      
      ```


2) Added the excecution path for the library just installed inside the config/initializers/wicked_pdf.rb
      ```
        # enable_local_file_access: true <-- comment this line
        exe_path: '/usr/local/bin/wkhtmltopdf'
      
      ```

Doing it this way allows us to prepare all of our instances with AWS's newer Linux versions, hoping it works in the future with this workarounds.

**Comment by ohadbenita** [comment]
I'm trying to find a way to build a Lambda layer for Amazonlinux 2023 based runtimes (such as Python 3.12), would appreciate some guidance if you could provide it, this is what I got so far:

```bash
#!/bin/bash
# Filename: build_lambda_layer.sh
# Purpose: Create a ZIP for an AWS Lambda layer on Amazon Linux 2023, ensuring
# that bin/, lib/, and fonts/ appear at the root of the ZIP.
#
# This script:
# 1. Installs wkhtmltopdf (built for CentOS 8) and system dependencies.
# 2. Copies the binary and libraries into /package/bin and /package/lib.
# 3. Copies a local fonts/ directory into /package/fonts.
# 4. cd's into /package and zips everything, ensuring the final ZIP has
#    bin/, lib/, and fonts/ at the root.
#
# Usage:
#  - Place a local 'fonts/' folder (and optional fonts.conf) next to this script.
#  - Run the script on Amazon Linux 2023 or in a Docker container.
#  - The resulting ZIP will be in /output/layer.zip.

set -e

echo "Updating system and installing base dependencies..."
dnf update -y
dnf install -y \
    fontconfig freetype libX11 libXext libXrender libXau libjpeg \
    xorg-x11-fonts-75dpi xorg-x11-fonts-Type1 urw-fonts \
    wget zip

echo "Installing wkhtmltox (wkhtmltopdf 0.12.6-1 for CentOS 8)..."
ARCH=x86_64
dnf install -y "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.centos8.${ARCH}.rpm"

echo "Creating staging directories..."
mkdir -p /package/bin /package/lib /package/fonts

echo "Copying wkhtmltopdf binary..."
cp /usr/local/bin/wkhtmltopdf /package/bin/

echo "Copying required shared libraries..."
# You can tailor this to your actual ldd output.
cp /usr/lib64/libX11.so.* /package/lib/ || true
cp /usr/lib64/libXext.so.* /package/lib/ || true
cp /usr/lib64/libXrender.so.* /package/lib/ || true
cp /usr/lib64/libfontconfig.so.* /package/lib/ || true
cp /usr/lib64/libfreetype.so.* /package/lib/ || true
cp /usr/lib64/libjpeg.so.* /package/lib/ || true
cp /usr/lib64/libXau.so.* /package/lib/ || true
cp /usr/lib64/libssl.so.* /package/lib/ || true
cp /usr/lib64/libcrypto.so.* /package/lib/ || true

echo "Copying local fonts..."
# If you have a local 'fonts' folder next to this script, copy it to /package/fonts
if [ -d "./fonts" ]; then
  cp -r ./fonts/* /package/fonts/
fi

# If you also have a fonts.conf, and you want it in the ZIP root:
if [ -f "./fonts.conf" ]; then
  cp ./fonts.conf /package/
fi

echo "Zipping the layer with bin/, lib/, and fonts/ at the root..."
mkdir -p /output
cd /package
zip -r /output/layer.zip .

echo "Done! The layer ZIP is at /output/layer.zip"
echo "Check its contents with: unzip -l /output/layer.zip"
exit 0
```

And running it using:

```
docker run --rm \
  -v "$(pwd)/output":/output \
  -v "$(pwd)/fonts":/build/fonts \
  -v "$(pwd)/build_lambda_layer.sh":/build/build_lambda_layer.sh \
  -w /build \
  amazonlinux:2023 \
  bash /build/build_lambda_layer.sh
```

The thing is I own an Apple chip Macbook pro which architecture is different from the Lambda's (x86_64 vs amd64).

**Comment by rbpltr** [comment]
You should probably look to run this build on a build server instead of your local to ensure consistent runs. I'd also recommend building for both Lambda architectures so you can easily change later down the line.

Swap this hardcoded architecture
```sh
ARCH=x86_64
dnf install -y "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.centos8.${ARCH}.rpm"
```

for this dynamically determined one
```sh
dnf install -y "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.centos8.$(uname -m).rpm"
```

and then add a `--platform linux/amd64` option to your `docker run` command to use the x86_64 architecture emulation.

**Comment by ohadbenita** [comment]
For anyone interested in an Amazon Linux 2023 compatible layer, I've built one using docker & tested it, for [anyone interested](https://github.com/ohadbenita/wkhtmltopdf-amazon-linux-2023-lambda-layer)

**Comment by lvenki94** [comment]
@ohadbenita Thank you, this helps.

**Comment by foxy14122021-gif** [comment]
Maybe it will be useful for some dotnet devs:

FROM public.ecr.aws/lambda/dotnet:9

RUN dnf -y install \
      wget \
      fontconfig \
      xorg-x11-font-utils \
      cabextract \
      xorg-x11-fonts-75dpi \
      xorg-x11-fonts-Type1 \
    && dnf clean all

RUN cd /tmp \
    && wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox-0.12.6.1-3.almalinux9.x86_64.rpm \
    && dnf -y install $(rpm -qR wkhtmltox-0.12.6.1-3.almalinux9.x86_64.rpm | grep -v 'rpmlib(' | tr '\n' ' ') \
    && rpm -i wkhtmltox-0.12.6.1-3.almalinux9.x86_64.rpm \
    && rm wkhtmltox-0.12.6.1-3.almalinux9.x86_64.rpm

RUN cd /tmp \
    && wget https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm \
    && rpm -i msttcore-fonts-installer-2.6-1.noarch.rpm \
    && rm msttcore-fonts-installer-2.6-1.noarch.rpm
