### ISSUE TITLE
[Feature Request] - upgrade microdnf 3.10 and publish minimal image on docker hub

### ISSUE THREAD

**Issue by matejsp** [amazonlinux/amazon-linux-2023#595]
**Is your feature request related to a problem? Please describe.**
microdnf does not support replacing curl-minimal or gnupg2-minimal with it's full counterpart.
However version microdnf 3.10 supports swap command that would allow this.

Also publish docker minimal on official docker hub together with normal al2023.
https://hub.docker.com/_/amazonlinux/tags

**Describe the solution you'd like**
I would like to replace gnupg2 to full on al2023 docker minimal.

**Describe alternatives you've considered**
what we currently use in docker as workaround:
```
rpm -e curl-minimal --nodeps && dnf -y install curl --setopt=install_weak_deps=0
rpm -e gnupg2-minimal --nodeps && dnf -y install gnupg2 --setopt=install_weak_deps=0
```

**Comment by stewartsmith** [comment]
Is there any reason you can't pull the minimal container image from ECR?

We do have an (internal) backlog item for publishing to DockerHub. We hadn't published it there yet as updating images on DockerHub requires humans merging pull requests and a request to not update the images more than once a week, while with ECR we can programmatically publish updates - so we decided to see what the demand was for it being available on DockerHub rather than just ECR. This is the first request we've gotten :)

**Comment by stewartsmith** [comment]
For `microdnf` 3.10, likely coming to 2023.6.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.6.20241010.html the `microdnf` in AL2023 is 3.10.

I'll point to https://github.com/amazonlinux/amazon-linux-2023/issues/724 for tracking discrepancies between dockerhub and ecr.
