### ISSUE TITLE
[Feature Request] - any plan to release qemu / kvm images?

### ISSUE THREAD

**Issue by zhouziyang** [amazonlinux/amazon-linux-2023#65]
or `amazonlinux 2` with `5.10` kernel image. I tried to build `5.10` by myself, but boot failed.
Thanks~~

**Comment by elsaco** [comment]
@zhouziyang you can always download  `kvm` images from `https://cdn.amazonlinux.com/os-images` latest being:

`https://cdn.amazonlinux.com/os-images/2.0.20211201.0/kvm/amzn2-kvm-2.0.20211201.0-x86_64.xfs.gpt.qcow2`

**Comment by stewartsmith** [comment]
I'm going to close this issue in favor of https://github.com/amazonlinux/amazon-linux-2023/issues/102 as more discussion has occurred over there (even though this issue was filed first).

One GitHub issue per issue is much easier to manage, so we'll focus on https://github.com/amazonlinux/amazon-linux-2023/issues/102

**Comment by stewartsmith** [comment]
(I wish I could work out how to make github say "duplicate" rather than "not planned now" because that is the intent I have, and resolving as "done" is also incorrect... grrr... computers)
