### ISSUE TITLE
[Package Request] - nginx 1.26

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#718]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
niginx 1.26
**Is this an update to existing package or new package request?**
update from 1.24
**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
N/A
**Any additional information you'd like to include. (use-cases, etc)**
I understand that AL2023 is Enterprise Linux but could nginx 1.26 be added?

**Comment by MayuraRam** [comment]
This upgrade is needed as it is being flagged by security scanners. The sooner it can be updated the better!

**Comment by maanisim** [comment]
I could confirm the same behaviour on my end on AL2023
```
sh-5.2$ /usr/sbin/nginx -v
nginx version: nginx/1.24.0
sh-5.2$ nginx -v
nginx version: nginx/1.24.0
```

I can see that Nginx is still being actively updated with security patches until 2028-03-15 [1] as such the security of Nginx 1.24 should not be a concern.

You can find the same information with regards to the security patches provided by AWS here [2]:

Q: Why does a security scanner report an unfixed CVE in an Amazon Linux package when an Amazon Linux Security Advisory claims the CVE to be fixed in that version?

A: Amazon Linux, like most Linux distributions, routinely backports security fixes to stable package versions vended in its repositories. When these packages are updated with a backport, the Amazon Linux security bulletin for the particular issue will list the specific package version(s) in which the issue is fixed for Amazon Linux. Security scanners that rely on versioning from a project’s authors sometimes won’t pick up that a given CVE fix has been applied in an older version. Customers can refer to Amazon Linux Security Center (ALAS) for updates regarding security issues and fixes.

References:
[1] https://docs.aws.amazon.com/linux/al2023/release-notes/support-info-by-support-statement.html#support-info-by-support-statement-eol_nginx
[2] https://aws.amazon.com/linux/amazon-linux-2023/faqs/

**Comment by epotocko** [comment]
Nginx 1.25.1+ is required to use an AWS NLB with TLS Termination and HTTP/2 enabled forwarding traffic to Nginx. 
More info: 
https://github.com/kubernetes/ingress-nginx/issues/10390
https://trac.nginx.org/nginx/ticket/816

**Comment by Colkadome** [comment]
Nginx 1.24 is being flagged by a security scanner for our servers, and is listed as a [legacy version](https://nginx.org/en/download.html), so this would help me to update to Nginx 1.26+

**Comment by yumin** [comment]
Nginx 1.24 is flagged for security concerns by the IT team from one of my potential customers, so updating to 1.26 will be tremendously helpful.

**Comment by bradnak** [comment]
I actually found that Nginx has yum repositories for both Amazon Linux 2 and 2023. https://nginx.org/en/linux_packages.html#Amazon-Linux

**Comment by yumin** [comment]
> I actually found that Nginx has yum repositories for both Amazon Linux 2 and 2023. https://nginx.org/en/linux_packages.html#Amazon-Linux

I tried this on AL2023 recently, but the "stable" repo of nginx for AL2023 still points to 1.24

**Comment by bradnak** [comment]
> > I actually found that Nginx has yum repositories for both Amazon Linux 2 and 2023. https://nginx.org/en/linux_packages.html#Amazon-Linux
> 
> I tried this on AL2023 recently, but the "stable" repo of nginx for AL2023 still points to 1.24

Damn, that's a real shame. I was hoping to use this to install 1.26 on my AL2023 server. I wonder what "mainline" points to then?

**Comment by MrVJTod** [comment]
Understanding that 
> Nginx is still being actively updated with security patches until 2028-03-15 [1] as such the security of Nginx 1.24 should not be a concern.
> [1] https://docs.aws.amazon.com/linux/al2023/release-notes/support-info-by-support-statement.html#support-info-by-support-statement-eol_nginx

it would still be nice to see newer versions of nginx supported.

For those who haven't, it is recommended to enable "server_tokens off;" so that you stop broadcasting your nginx version to the world.

**Comment by daniejstriata** [comment]
The nginx.org repo repo is definitely publishing v1.26:
https://nginx.org/packages/amzn/2023/x86_64/RPMS/

**Comment by daniejstriata** [comment]
I got nginx 1.26.2 with latest 2023.6.20241028 release! Thanks!
